# puts "Seeding Users..."

# 25.times do
#   User.create!(
#     first_name: Faker::Name.unique.first_name,
#     last_name: Faker::Name.last_name,
#     email: Faker::Internet.unique.email,
#     handle: Faker::FunnyName.name
#   )
# end

# puts "Seeding Posts..."

# 200.times do
#   Post.create(
#     image: Faker::LoremFlickr.image(size: "750x750", search_terms: ['person', 'nature'], match_all: true),
#     caption: Faker::GreekPhilosophers.quote,
#     likes: rand(0..100),
#     dislikes: rand(0..100),
#     user_id: rand(1..25)
#   )
# end

# puts "Seeding Comments..."

# 500.times do
#   Comment.create(
#     content: Faker::TvShows::Seinfeld.quote,
#     post_id: rand(1..200),
#     user_id: rand(1..25)
#   )
# end

# puts "Seeding Comment_Comments..."

# 750.times do
#   CommentComment.create(
#     content: Faker::JapaneseMedia::StudioGhibli.quote,
#     comment_id: rand(1..500),
#     user_id: rand(1..25)
#   )
# end

# puts "Finished First Seed"



# puts "Seeding Follows"

# 100.times do
#     Follow.create!(
#         follower_id: rand(1..25),
#         following_id: rand(1..25) 
#     )
# end

# puts "Updating Images"

#     Post.find(1).update!(image: "https://i.ibb.co/ysh4h67/File-1.jpg")
#     Post.find(2).update!(image: "https://i.ibb.co/8K59dwt/File-2.jpg")
#     Post.find(3).update!(image: "https://i.ibb.co/Bcq5Frg/File-3.jpg")
#     Post.find(4).update!(image: "https://i.ibb.co/J7vQM3W/File-4.jpg")
#     Post.find(5).update!(image: "https://i.ibb.co/cJsbMtG/File-5.jpg")
#     Post.find(6).update!(image: "https://i.ibb.co/xz2Vvs0/File-6.jpg")
#     Post.find(7).update!(image: "https://i.ibb.co/F3QW4R6/File-7.jpg")
#     Post.find(8).update!(image: "https://i.ibb.co/nMjn37Z/File-8.jpg")
#     Post.find(9).update!(image: "https://i.ibb.co/GW1NkcX/File-9.jpg")
#     Post.find(10).update!(image: "https://i.ibb.co/MCN4nv5/File-10.jpg")
#     Post.find(11).update!(image: "https://i.ibb.co/GJCF33G/File-11.jpg")
#     Post.find(12).update!(image: "https://i.ibb.co/yp2NrHt/File-12.jpg")
#     Post.find(13).update!(image: "https://i.ibb.co/StS3Qsk/File-13.jpg")
#     Post.find(14).update!(image: "https://i.ibb.co/6vVRWnB/File-14.jpg")
#     Post.find(15).update!(image: "https://i.ibb.co/xsDrzN8/File-15.jpg")
#     Post.find(16).update!(image: "https://i.ibb.co/tZpRfxm/File-16.jpg")
#     Post.find(17).update!(image: "https://i.ibb.co/2W93KYz/File-17.jpg")
#     Post.find(18).update!(image: "https://i.ibb.co/QCJpNxs/File-18.jpg")
#     Post.find(19).update!(image: "https://i.ibb.co/0rKwkxb/File-19.jpg")
#     Post.find(20).update!(image: "https://i.ibb.co/DWT16WM/File-20.jpg")
#     Post.find(21).update!(image: "https://i.ibb.co/zHpTK71/File-21.jpg")
#     Post.find(22).update!(image: "https://i.ibb.co/0qRnyP2/File-22.jpg")
#     Post.find(23).update!(image: "https://i.ibb.co/PY3v9tM/File-23.jpg")
#     Post.find(24).update!(image: "https://i.ibb.co/d6HtVg9/File-24.jpg")
#     Post.find(25).update!(image: "https://i.ibb.co/MgH7WDj/File-25.jpg")
#     Post.find(26).update!(image: "https://i.ibb.co/wChY8bf/File-26.jpg")
#     Post.find(27).update!(image: "https://i.ibb.co/R9WK5MY/File-27.jpg")
#     Post.find(28).update!(image: "https://i.ibb.co/K0mRknn/File-28.jpg")
#     Post.find(29).update!(image: "https://i.ibb.co/6HxC7HV/File-29.jpg")
#     Post.find(30).update!(image: "https://i.ibb.co/dpt0Yy6/File-30.jpg")
#     Post.find(31).update!(image: "https://i.ibb.co/xL8Nvm2/File-31.jpg")
#     Post.find(32).update!(image: "https://i.ibb.co/ckmr3nc/File-32.jpg")
#     Post.find(33).update!(image: "https://i.ibb.co/Jpgr805/File-33.jpg")
#     Post.find(34).update!(image: "https://i.ibb.co/4NMz2qG/File-34.jpg")
#     Post.find(35).update!(image: "https://i.ibb.co/37g91MX/File-35.jpg")
#     Post.find(36).update!(image: "https://i.ibb.co/sqH8XVV/File-36.jpg")
#     Post.find(37).update!(image: "https://i.ibb.co/SVn9tBq/File-37.jpg")
#     Post.find(38).update!(image: "https://i.ibb.co/0XkycGH/File-38.jpg")
#     Post.find(39).update!(image: "https://i.ibb.co/R9L9b4B/File-39.jpg")
#     Post.find(40).update!(image: "https://i.ibb.co/ZxcMFsC/File-40.jpg")
#     Post.find(41).update!(image: "https://i.ibb.co/khYxCBk/File-41.jpg")
#     Post.find(42).update!(image: "https://i.ibb.co/9V8yGjQ/File-42.jpg")
#     Post.find(43).update!(image: "https://i.ibb.co/zGgxp6R/File-43.jpg")
#     Post.find(44).update!(image: "https://i.ibb.co/0cS5bkP/File-44.jpg")
#     Post.find(45).update!(image: "https://i.ibb.co/M1WHFK6/File-45.jpg")
#     Post.find(46).update!(image: "https://i.ibb.co/MMztk4F/File-46.jpg")
#     Post.find(47).update!(image: "https://i.ibb.co/PrNddG9/File-47.jpg")
#     Post.find(48).update!(image: "https://i.ibb.co/db9NkhQ/File-48.jpg")
#     Post.find(49).update!(image: "https://i.ibb.co/WKCy73X/File-49.jpg")
#     Post.find(50).update!(image: "https://i.ibb.co/2km9v3R/File-50.jpg")
#     Post.find(51).update!(image: "https://i.ibb.co/mT0vKtH/File-51.jpg")
#     Post.find(52).update!(image: "https://i.ibb.co/j84bHF7/File-52.jpg")
#     Post.find(53).update!(image: "https://i.ibb.co/PC96g4K/File-53.jpg")
#     Post.find(54).update!(image: "https://i.ibb.co/KK3ZSZh/File-54.jpg")
#     Post.find(55).update!(image: "https://i.ibb.co/dgSh3KC/File-55.jpg")
#     Post.find(56).update!(image: "https://i.ibb.co/QFhLcxC/File-56.jpg")
#     Post.find(57).update!(image: "https://i.ibb.co/FbpKxWS/File-57.jpg")
#     Post.find(58).update!(image: "https://i.ibb.co/k58PK1s/File-58.jpg")
#     Post.find(59).update!(image: "https://i.ibb.co/xm1KSd4/File-59.jpg")
#     Post.find(60).update!(image: "https://i.ibb.co/tBr9LFH/File-60.jpg")
#     Post.find(61).update!(image: "https://i.ibb.co/Gkr2PDz/File-61.jpg")
#     Post.find(62).update!(image: "https://i.ibb.co/Y7zJp9P/File-62.jpg")
#     Post.find(63).update!(image: "https://i.ibb.co/vcWHszJ/File-63.jpg")
#     Post.find(64).update!(image: "https://i.ibb.co/wLLXpCS/File-64.jpg")
#     Post.find(65).update!(image: "https://i.ibb.co/6gj0bvJ/File-65.jpg")
#     Post.find(66).update!(image: "https://i.ibb.co/fSMLyrH/File-66.jpg")
#     Post.find(67).update!(image: "https://i.ibb.co/9ydtsmG/File-67.jpg")
#     Post.find(68).update!(image: "https://i.ibb.co/BqsC3bd/File-68.jpg")
#     Post.find(69).update!(image: "https://i.ibb.co/v1yJkZZ/File-69.jpg")
#     Post.find(70).update!(image: "https://i.ibb.co/k229ryS/File-70.jpg")
#     Post.find(71).update!(image: "https://i.ibb.co/FwWg0Ft/File-71.jpg")
#     Post.find(72).update!(image: "https://i.ibb.co/fp3f4XS/File-72.jpg")
#     Post.find(73).update!(image: "https://i.ibb.co/7nPgJfH/File-73.jpg")
#     Post.find(74).update!(image: "https://i.ibb.co/HPc646M/File-74.jpg")
#     Post.find(75).update!(image: "https://i.ibb.co/XxT3FP2/File-75.jpg")
#     Post.find(76).update!(image: "https://i.ibb.co/M2Cc85F/File-76.jpg")
#     Post.find(77).update!(image: "https://i.ibb.co/pLjPL8T/File-77.jpg")
#     Post.find(78).update!(image: "https://i.ibb.co/vBm8rnf/File-78.jpg")
#     Post.find(79).update!(image: "https://i.ibb.co/n1zL9Wk/File-79.jpg")
#     Post.find(80).update!(image: "https://i.ibb.co/phsMRbP/File-80.jpg")
#     Post.find(81).update!(image: "https://i.ibb.co/ZMs2GZG/File-81.jpg")
#     Post.find(82).update!(image: "https://i.ibb.co/gwR6yG0/File-82.jpg")
#     Post.find(83).update!(image: "https://i.ibb.co/gJfQQtN/File-83.jpg")
#     Post.find(84).update!(image: "https://i.ibb.co/Rv0Zcz2/File-84.jpg")
#     Post.find(85).update!(image: "https://i.ibb.co/b19fMZ7/File-85.jpg")
#     Post.find(86).update!(image: "https://i.ibb.co/cxKBNHC/File-86.jpg")
#     Post.find(87).update!(image: "https://i.ibb.co/p267CbG/File-87.jpg")
#     Post.find(88).update!(image: "https://i.ibb.co/5134SbR/File-88.jpg")
#     Post.find(89).update!(image: "https://i.ibb.co/9pfFGH1/File-89.jpg")
#     Post.find(90).update!(image: "https://i.ibb.co/CV5YLYt/File-90.jpg")
#     Post.find(91).update!(image: "https://i.ibb.co/3RDy7zx/File-91.jpg")
#     Post.find(92).update!(image: "https://i.ibb.co/KLNBYmB/File-92.jpg")
#     Post.find(93).update!(image: "https://i.ibb.co/WBrmXh1/File-93.jpg")
#     Post.find(94).update!(image: "https://i.ibb.co/18HD0pv/File-94.jpg")
#     Post.find(95).update!(image: "https://i.ibb.co/wdVdDjM/File-95.jpg")
#     Post.find(96).update!(image: "https://i.ibb.co/VC4GJfP/File-96.jpg")
#     Post.find(97).update!(image: "https://i.ibb.co/fYtJD6p/File-97.jpg")
#     Post.find(98).update!(image: "https://i.ibb.co/8DFVDcq/File-98.jpg")
#     Post.find(99).update!(image: "https://i.ibb.co/3C9QmXZ/File-99.jpg")
#     Post.find(100).update!(image: "https://i.ibb.co/5RzT764/File-100.jpg")
#     Post.find(101).update!(image: "https://i.ibb.co/2ZPZ8tM/File-101.jpg")
#     Post.find(102).update!(image: "https://i.ibb.co/QJP8Jv5/File-102.jpg")
#     Post.find(103).update!(image: "https://i.ibb.co/N3wDdnc/File-103.jpg")
#     Post.find(104).update!(image: "https://i.ibb.co/Px4D2cq/File-104.jpg")
#     Post.find(105).update!(image: "https://i.ibb.co/SKHzkt2/File-105.jpg")
#     Post.find(106).update!(image: "https://i.ibb.co/XWpPQyB/File-106.jpg")
#     Post.find(107).update!(image: "https://i.ibb.co/rZcm54r/File-107.jpg")
#     Post.find(108).update!(image: "https://i.ibb.co/MVBGWct/File-108.jpg")
#     Post.find(109).update!(image: "https://i.ibb.co/WFfLNhk/File-109.jpg")
#     Post.find(110).update!(image: "https://i.ibb.co/jMGHbrV/File-110.jpg")
#     Post.find(111).update!(image: "https://i.ibb.co/gM5k951/File-111.jpg")
#     Post.find(112).update!(image: "https://i.ibb.co/gTd7Pwp/File-112.jpg")
#     Post.find(113).update!(image: "https://i.ibb.co/GPWc8b2/File-113.jpg")
#     Post.find(114).update!(image: "https://i.ibb.co/k5xy3zf/File-114.jpg")
#     Post.find(115).update!(image: "https://i.ibb.co/vBpYMXq/File-115.jpg")
#     Post.find(116).update!(image: "https://i.ibb.co/Sv5s3d7/File-116.jpg")
#     Post.find(117).update!(image: "https://i.ibb.co/VLSw2hj/File-117.jpg")
#     Post.find(118).update!(image: "https://i.ibb.co/LCp66ZC/File-118.jpg")
#     Post.find(119).update!(image: "https://i.ibb.co/7pTQhVv/File-119.jpg")
#     Post.find(120).update!(image: "https://i.ibb.co/xLmSPQW/File-120.jpg")
#     Post.find(121).update!(image: "https://i.ibb.co/DWnjbYQ/File-121.jpg")
#     Post.find(122).update!(image: "https://i.ibb.co/3zXSp7v/File-122.jpg")
#     Post.find(123).update!(image: "https://i.ibb.co/wQtPx3d/File-123.jpg")
#     Post.find(124).update!(image: "https://i.ibb.co/Bw8Lk5R/File-124.jpg")
#     Post.find(125).update!(image: "https://i.ibb.co/sVPFCQ4/File-125.jpg")
#     Post.find(126).update!(image: "https://i.ibb.co/LpS4tXT/File-126.jpg")
#     Post.find(127).update!(image: "https://i.ibb.co/8Ywg9kB/File-127.jpg")
#     Post.find(128).update!(image: "https://i.ibb.co/w75LzMn/File-128.jpg")
#     Post.find(129).update!(image: "https://i.ibb.co/Lrp2Cts/File-129.jpg")
#     Post.find(130).update!(image: "https://i.ibb.co/3vtt6gs/File-130.jpg")
#     Post.find(131).update!(image: "https://i.ibb.co/QMWpj3D/File-131.jpg")
#     Post.find(132).update!(image: "https://i.ibb.co/t3hY9qy/File-132.jpg")
#     Post.find(133).update!(image: "https://i.ibb.co/C7whGWd/File-133.jpg")
#     Post.find(134).update!(image: "https://i.ibb.co/8cwzSCh/File-134.jpg")
#     Post.find(135).update!(image: "https://i.ibb.co/DtW9Rcj/File-135.jpg")
#     Post.find(136).update!(image: "https://i.ibb.co/f1D71cT/File-136.jpg")
#     Post.find(137).update!(image: "https://i.ibb.co/PmNCz42/File-137.jpg")
#     Post.find(138).update!(image: "https://i.ibb.co/z2YpcVK/File-138.jpg")
#     Post.find(139).update!(image: "https://i.ibb.co/9yPnXLt/File-139.jpg")
#     Post.find(140).update!(image: "https://i.ibb.co/0VSR35Q/File-140.jpg")
#     Post.find(141).update!(image: "https://i.ibb.co/M22cJsD/File-141.jpg")
#     Post.find(142).update!(image: "https://i.ibb.co/PCrnm4Y/File-142.jpg")
#     Post.find(143).update!(image: "https://i.ibb.co/3v613rP/File-143.jpg")
#     Post.find(144).update!(image: "https://i.ibb.co/cFR8nW7/File-144.jpg")
#     Post.find(145).update!(image: "https://i.ibb.co/m61ddxK/File-145.jpg")
#     Post.find(146).update!(image: "https://i.ibb.co/fnmJfTq/File-146.jpg")
#     Post.find(147).update!(image: "https://i.ibb.co/m6FM4sk/File-147.jpg")
#     Post.find(148).update!(image: "https://i.ibb.co/cXhJQG3/File-148.jpg")
#     Post.find(149).update!(image: "https://i.ibb.co/9cBTmZp/File-149.jpg")
#     Post.find(150).update!(image: "https://i.ibb.co/Yhv9ftG/File-150.jpg")
#     Post.find(151).update!(image: "https://i.ibb.co/kyChqjL/File-151.jpg")
#     Post.find(152).update!(image: "https://i.ibb.co/BwFD5rb/File-152.jpg")
#     Post.find(153).update!(image: "https://i.ibb.co/pWg5Crz/File-153.jpg")
#     Post.find(154).update!(image: "https://i.ibb.co/89LMNZK/File-154.jpg")
#     Post.find(155).update!(image: "https://i.ibb.co/jLmsMnX/File-155.jpg")
#     Post.find(156).update!(image: "https://i.ibb.co/ZYWp6CV/File-156.jpg")
#     Post.find(157).update!(image: "https://i.ibb.co/1zZmRzj/File-157.jpg")
#     Post.find(158).update!(image: "https://i.ibb.co/KqkkFF9/File-158.jpg")
#     Post.find(159).update!(image: "https://i.ibb.co/d0SyMhN/File-159.jpg")
#     Post.find(160).update!(image: "https://i.ibb.co/YNk3cjC/File-160.jpg")
#     Post.find(161).update!(image: "https://i.ibb.co/TKgMWZt/File-161.jpg")
#     Post.find(162).update!(image: "https://i.ibb.co/8scGYJN/File-162.jpg")
#     Post.find(163).update!(image: "https://i.ibb.co/WVVXs8Z/File-163.jpg")
#     Post.find(164).update!(image: "https://i.ibb.co/vDsYDYq/File-164.jpg")
#     Post.find(165).update!(image: "https://i.ibb.co/pZSz33f/File-165.jpg")
#     Post.find(166).update!(image: "https://i.ibb.co/v4Y8PkG/File-166.jpg")
#     Post.find(167).update!(image: "https://i.ibb.co/r7QwBQg/File-167.jpg")
#     Post.find(168).update!(image: "https://i.ibb.co/wSwHLZ5/File-168.jpg")
#     Post.find(169).update!(image: "https://i.ibb.co/jZ9STfN/File-169.jpg")
#     Post.find(170).update!(image: "https://i.ibb.co/VmM3CJH/File-170.jpg")
#     Post.find(171).update!(image: "https://i.ibb.co/ws1nSFR/File-171.jpg")
#     Post.find(172).update!(image: "https://i.ibb.co/DDXg9Kd/File-172.jpg")
#     Post.find(173).update!(image: "https://i.ibb.co/KqJLZ6m/File-173.jpg")
#     Post.find(174).update!(image: "https://i.ibb.co/5cVYwBp/File-174.jpg")
#     Post.find(175).update!(image: "https://i.ibb.co/Ytmm5Nz/File-175.jpg")
#     Post.find(176).update!(image: "https://i.ibb.co/XY6ptbd/File-176.jpg")
#     Post.find(177).update!(image: "https://i.ibb.co/n6zGKm0/File-177.jpg")
#     Post.find(178).update!(image: "https://i.ibb.co/yQXGj4Q/File-178.jpg")
#     Post.find(179).update!(image: "https://i.ibb.co/vDfmpW2/File-179.jpg")
#     Post.find(180).update!(image: "https://i.ibb.co/pdrCwCf/File-180.jpg")
#     Post.find(181).update!(image: "https://i.ibb.co/ZY2SjRR/File-181.jpg")
#     Post.find(182).update!(image: "https://i.ibb.co/h2Mjdgy/File-182.jpg")
#     Post.find(183).update!(image: "https://i.ibb.co/F8pVbP6/File-183.jpg")
#     Post.find(184).update!(image: "https://i.ibb.co/Yt81bm9/File-184.jpg")
#     Post.find(185).update!(image: "https://i.ibb.co/nrCJfcQ/File-185.jpg")
#     Post.find(186).update!(image: "https://i.ibb.co/V3MCDrb/File-186.jpg")
#     Post.find(187).update!(image: "https://i.ibb.co/qRVm9sW/File-187.jpg")
#     Post.find(188).update!(image: "https://i.ibb.co/5BX0twc/File-188.jpg")
#     Post.find(189).update!(image: "https://i.ibb.co/vZMHB4D/File-189.jpg")
#     Post.find(190).update!(image: "https://i.ibb.co/0fd00jP/File-190.jpg")
#     Post.find(191).update!(image: "https://i.ibb.co/4sT9L24/File-191.jpg")
#     Post.find(192).update!(image: "https://i.ibb.co/JcNXN9d/File-192.jpg")
#     Post.find(193).update!(image: "https://i.ibb.co/8dpbH2k/File-193.jpg")
#     Post.find(194).update!(image: "https://i.ibb.co/2gzBLyr/File-194.jpg")
#     Post.find(195).update!(image: "https://i.ibb.co/0YxZ33J/File-195.jpg")
#     Post.find(196).update!(image: "https://i.ibb.co/0tBJRNT/File-196.jpg")
#     Post.find(197).update!(image: "https://i.ibb.co/khVfrHk/File-197.jpg")
#     Post.find(198).update!(image: "https://i.ibb.co/VvNVXbS/File-198.jpg")
#     Post.find(199).update!(image: "https://i.ibb.co/Fg2r7qB/File-199.jpg")
#     Post.find(200).update!(image: "https://i.ibb.co/mJ2kmb2/File-200.jpg")


# puts "Updating Passwords"

# User.find(1).update(password: '1')
#   User.find(2).update(password: '2')
#   User.find(3).update(password: '3')
#   User.find(4).update(password: '4')
#   User.find(5).update(password: '5')
#   User.find(6).update(password: '6')
#   User.find(7).update(password: '7')
#   User.find(8).update(password: '8')
#   User.find(9).update(password: '9')
#   User.find(10).update(password: '10')
#   User.find(11).update(password: '11')
#   User.find(12).update(password: '12')
#   User.find(13).update(password: '13')
#   User.find(14).update(password: '14')
#   User.find(15).update(password: '15')
#   User.find(16).update(password: '16')
#   User.find(17).update(password: '17')
#   User.find(18).update(password: '18')
#   User.find(19).update(password: '19')
#   User.find(20).update(password: '20')
#   User.find(21).update(password: '21')
#   User.find(22).update(password: '22')
#   User.find(23).update(password: '23')
#   User.find(24).update(password: '24')
#   User.find(25).update(password: '25')

#   puts "Updating emails"

# User.find(1).update(email: "1@1.com")
# User.find(2).update(email: "2@2.com")
# User.find(3).update(email: "3@3.com")
# User.find(4).update(email: "4@4.com")
# User.find(5).update(email: "5@5.com")
# User.find(6).update(email: "6@6.com")
# User.find(7).update(email: "7@7.com")
# User.find(8).update(email: "8@8.com")
# User.find(9).update(email: "9@9.com")
# User.find(10).update(email: "10@10.com")
# User.find(11).update(email: "11@11.com")
# User.find(12).update(email: "12@12.com")
# User.find(13).update(email: "13@13.com")
# User.find(14).update(email: "14@14.com")
# User.find(15).update(email: "15@15.com")
# User.find(16).update(email: "16@16.com")
# User.find(17).update(email: "17@17.com")
# User.find(18).update(email: "18@18.com")
# User.find(19).update(email: "19@19.com")
# User.find(20).update(email: "20@20.com")
# User.find(21).update(email: "21@21.com")
# User.find(22).update(email: "22@22.com")
# User.find(23).update(email: "23@23.com")
# User.find(24).update(email: "24@24.com")
# User.find(25).update(email: "25@25.com")

# puts "Adding Avatars"

# User.find(1).update(avatar: "https://i.ibb.co/BG9Df2g/1.jpg")
#   User.find(2).update(avatar: "https://i.ibb.co/YbN29r3/2.jpg")
#   User.find(3).update(avatar: "https://i.ibb.co/D9wxpDB/3.jpg")
#   User.find(4).update(avatar: "https://i.ibb.co/GxGRxjr/4.png")
#   User.find(5).update(avatar: "https://i.ibb.co/M2hpVtC/5.jpg")
#   User.find(6).update(avatar: "https://i.ibb.co/nBxD4SJ/6.png")
#   User.find(7).update(avatar: "https://i.ibb.co/d4nW4k7/7.jpg")
#   User.find(8).update(avatar: "https://i.ibb.co/mFkg1LF/8.jpg")
#   User.find(9).update(avatar: "https://i.ibb.co/p2szsG4/9.jpg")
#   User.find(10).update(avatar: "https://i.ibb.co/ThPJT5B/10.jpg")
#   User.find(11).update(avatar: "https://i.ibb.co/FJYypyy/11.png")
#   User.find(12).update(avatar: "https://i.ibb.co/0m3kR94/12.png")
#   User.find(13).update(avatar: "https://i.ibb.co/wcwZYhH/13.png")
#   User.find(14).update(avatar: "https://i.ibb.co/SwgQqF4/14.png")
#   User.find(15).update(avatar: "https://i.ibb.co/G3XPTvm/15.png")
#   User.find(16).update(avatar: "https://i.ibb.co/LvjKFLP/16.jpg")
#   User.find(17).update(avatar: "https://i.ibb.co/0r5NXkF/17.jpg")
#   User.find(18).update(avatar: "https://i.ibb.co/b1YP0NH/18.jpg")
#   User.find(19).update(avatar: "https://i.ibb.co/mN6W9hn/19.png")
#   User.find(20).update(avatar: "https://i.ibb.co/gRgZFfs/20.jpg")
#   User.find(21).update(avatar: "https://i.ibb.co/CvMB6rg/21.png")
#   User.find(22).update(avatar: "https://i.ibb.co/PQyMkC8/22.jpg")
#   User.find(23).update(avatar: "https://i.ibb.co/QkH07Cy/23.png")
#   User.find(24).update(avatar: "https://i.ibb.co/kJkRT3Q/24.png")
#   User.find(25).update(avatar: "https://i.ibb.co/DMHBL4z/25.jpg")

#   puts 'Updating Handle, First and Last Names...'

# User.find(1).update(handle: "C.Erlendson")
#   User.find(2).update(handle: "C.Kozey")
#   User.find(3).update(handle: "A.Fisher")
#   User.find(4).update(handle: "A.Otaola")
#   User.find(5).update(handle: "A.Fo")
#   User.find(6).update(handle: "A.Ramsumair")
#   User.find(7).update(handle: "C.Zhong")
#   User.find(8).update(handle: "D.Yim")
#   User.find(9).update(handle: "D.Peterson")
#   User.find(10).update(handle: "H.Razak")
#   User.find(11).update(handle: "J.Cogan")
#   User.find(12).update(handle: "J.Prawdzik")
#   User.find(13).update(handle: "J.Bonventre")
#   User.find(14).update(handle: "K.Mak")
#   User.find(15).update(handle: "O.Radick")
#   User.find(16).update(handle: "R.Katzman")
#   User.find(17).update(handle: "S.Adelson")
#   User.find(18).update(handle: "S.Otalora")
#   User.find(19).update(handle: "T.Tal")
#   User.find(20).update(handle: "T.Judge")
#   User.find(21).update(handle: "V.Cadet")
#   User.find(22).update(handle: "J.Blanco")
#   User.find(23).update(handle: "C.Tiller")
#   User.find(24).update(handle: "M.Law")
#   User.find(25).update(handle: "A.Pisarenko")

#   User.find(1).update(first_name: "Chris")
#   User.find(2).update(first_name: "Charlie")
#   User.find(3).update(first_name: "Adam")
#   User.find(4).update(first_name: "Alejandro")
#   User.find(5).update(first_name: "Alton")
#   User.find(6).update(first_name: "Avinash")
#   User.find(7).update(first_name: "Corey")
#   User.find(8).update(first_name: "Daniel")
#   User.find(9).update(first_name: "Diana")
#   User.find(10).update(first_name: "Hassan")
#   User.find(11).update(first_name: "James")
#   User.find(12).update(first_name: "James")
#   User.find(13).update(first_name: "Joey")
#   User.find(14).update(first_name: "Kevin")
#   User.find(15).update(first_name: "Olivia")
#   User.find(16).update(first_name: "Rochelle")
#   User.find(17).update(first_name: "Samuel")
#   User.find(18).update(first_name: "Sebastian")
#   User.find(19).update(first_name: "Tomer")
#   User.find(20).update(first_name: "Tucker")
#   User.find(21).update(first_name: "Veronique")
#   User.find(22).update(first_name: "Jeryel")
#   User.find(23).update(first_name: "Chett")
#   User.find(24).update(first_name: "Michael")
#   User.find(25).update(first_name: "Alina")


# User.find(1).update(last_name: "Erlendson")
#   User.find(2).update(last_name: "Kozey")
#   User.find(3).update(last_name: "Fisher")
#   User.find(4).update(last_name: "Otaola")
#   User.find(5).update(last_name: "Fo")
#   User.find(6).update(last_name: "Ramsumair")
#   User.find(7).update(last_name: "Zhong")
#   User.find(8).update(last_name: "Yim")
#   User.find(9).update(last_name: "Peterson")
#   User.find(10).update(last_name: "Razak")
#   User.find(11).update(last_name: "Cogan")
#   User.find(12).update(last_name: "Prawdzik")
#   User.find(13).update(last_name: "Bonventre")
#   User.find(14).update(last_name: "Mak")
#   User.find(15).update(last_name: "Radick")
#   User.find(16).update(last_name: "Katzman")
#   User.find(17).update(last_name: "Adelson")
#   User.find(18).update(last_name: "Otalora")
#   User.find(19).update(last_name: "Tal")
#   User.find(20).update(last_name: "Judge")
#   User.find(21).update(last_name: "Cadet")
#   User.find(22).update(last_name: "Blanco")
#   User.find(23).update(last_name: "Tiller")
#   User.find(24).update(last_name: "Law")
#   User.find(25).update(last_name: "Pisarenko")



#   puts "Done seeding!"